# Generated by Django 5.0.1 on 2024-02-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ricette", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ricetta",
            options={"verbose_name_plural": "Ricette"},
        ),
        migrations.AlterField(
            model_name="ricetta",
            name="nome",
            field=models.TextField(unique=True),
        ),
    ]
