# Generated by Django 5.0.1 on 2024-02-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredienti", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingrediente",
            name="nome",
            field=models.TextField(unique=True),
        ),
    ]
