# Generated by Django 5.0.1 on 2024-02-01 16:23

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ricette", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ristorante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("indirizzo", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "cellulare",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("sito_web", models.URLField()),
                (
                    "ricette",
                    models.ManyToManyField(
                        related_name="ristoranti", to="ricette.ricetta"
                    ),
                ),
            ],
        ),
    ]
