# Generated by Django 5.0.1 on 2024-02-01 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ristoranti", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ristorante",
            options={"verbose_name_plural": "Ristoranti"},
        ),
        migrations.AlterUniqueTogether(
            name="ristorante",
            unique_together={("nome", "indirizzo")},
        ),
    ]
