name: Continuous Integration

on:
  push:
    branches:
      - main  # Sostituisci con il branch che desideri usare
  pull_request:
    branches:
      - main  # Sostituisci con il branch che desideri usare

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Sostituisci con la versione di Python usata nel tuo progetto

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Inserisci qui il comando per eseguire i tuoi test, ad esempio:
          python manage.py test
